version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn API:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
   
  web2:
    build: .
    command: sh -c "uvicorn objects:app --host 0.0.0.0 --port 8001"
    ports:
      - 8001:8001
    deploy:
      resources:
        limits:
          memory: 2G   
